.TH PYCP 1 "February 14, 2009"
.SH NAME
pycp \- cp with a progress bar
.SH SYNOPSIS
.B pycp
\fISOURCE\fR  \fIDESTINATION\fR
.SH DESCRIPTION
.B pycp
is a python script that fork a cp process and make use of
progressbar module.
.PP
\fISOURCE\fR
.B must
be an existing file. 
.br
\fIDESTINATION\fR must not already exist, unless it is a directory.
.PP
.SH OPTIONS
.TP 
\fB \-h, \-\-help\fR
Show summary of options.
.TP 
\fB\-\-version\fR
Show version of program.
.SH RESSOURCES
The sources of 
.B pycp
are hosted on gitorious: 
http://gitorious.org/projects/pycp
.br
.SH BUGS
.B pycp
does not handle copy of directories.
.SH AUTHOR
pycp was written by Yannick LM <yannicklm1337@gmail.com>
