.TH PYCP 1 "February 14, 2009"
.SH NAME
pycp \- cp with a progress bar
.SH SYNOPSIS
.B pycp
.RI "source" 
.RI "destination"
.SH DESCRIPTION
.B pycp
is a python script that fork a cp process and make use of
progressbar module.
.SH OPTIONS
.B \-h, \-\-help
Show summary of options.
.TP
.B  \-\-version
Show version of program.
.SH BUGS
pycp can only copy one file at a time
.SH AUTHOR
pycp was written by Yannick LM <yannicklm1337@gmail.com>
.PP
This manual page was written by Yannick LM <yannicklm1337@gmail.com>,
for the Debian project (but may be used by others).
