.TH PYCP 1 "March 8, 2009"
.SH NAME
pycp \- cp with a progress bar
.SH SYNOPSIS
.B pycp
\fISOURCE\fR  \fIDESTINATION\fR
.br
\fISOURCES...\fR \fIDIRECTORY\fR
.SH DESCRIPTION
.B pycp
is a python script that forks a `cp' process and makes use of
the progressbar module.
.PP
Copy \fISOURCE\fR in \fIDESTINATION\fR, or mutliple
\fISOURCES\fR into a \fIDIRECTORY\fR.
.br
By default, existing files will be overwritten
.SH OPTIONS
.TP
\fB \-h, \-\-help\fR
Show summary of options.
.TP
\fB\-\-version\fR
Show version of program.
.TP
\fB\-i, \-\-interactive\fR
Ask for confirmation before overwriting existing files
.SH RESSOURCES
The sources of
.B pycp
are hosted on gitorious:
http://gitorious.org/projects/pycp
.br
.SH BUGS
.B pycp
will take much longer than cp if you're trying to copy several little files
